[package]
name = "chapter-2"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
futures = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p" }
rand = "0.4"
tokio-io = "0.1"
tokio-stdin = "0.1"
