[package]
name = "chapter-1"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
futures = "0.1"
libp2p = { git = "https://github.com/tomaka/libp2p-rs", branch = "libp2p-facade" }
tokio-io = "0.1"
