[package]
name = "chapter-1"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
futures = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p", default-features = false }
tokio-core = "0.1"
tokio-io = "0.1"
